version: 0.4.0.{build}
skip_tags: true
image: Visual Studio 2017
clone_depth: 1
environment:
  NUGET_SECURE_TOKEN:
    secure: eF0Mu+Ky+FtngFJN7u4unv9l2ebEvlvfim9hPpWkRAc=
  nuget_user: adimosh@gmail.com
  nuget_password:
    secure: uBvWMFhy9DPgv2TIksG2FQ==
install:
- cmd: dotnet restore
nuget:
  account_feed: true
  project_feed: true
build_script:
- cmd: >-
    dotnet tools\CSProjAutoVersionIncrementer.dll IX.Observable\IX.Observable.csproj %APPVEYOR_BUILD_VERSION%

    dotnet build IX.Observable\IX.Observable.csproj -c Release
test_script:
- cmd: >-
    cd IX.Observable.UnitTests

    dotnet xunit

    cd ..
deploy_script:
- cmd: >-
    dotnet pack IX.Observable\IX.Observable.csproj -c Release --no-build

    nuget push IX.Observable\bin\Release\IX.Observable.%APPVEYOR_BUILD_VERSION%.nupkg -ApiKey %NUGET_SECURE_TOKEN% -Source https://ci.appveyor.com/nuget/adimosh-at-live-dot-com/api/v2/package